# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rajivsam.github.io/
baseurl:  
title: Rajiv Sambasivan
author: Rajiv Sambasivan
description: Personal blog and resume
avatar: profile.png
github: rajivsam # username
#twitter: username
linkedin: rajiv-sambasivan-0b6226
#stackoverflow:    #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
